In [1]:
#import necessary packages
import numpy as np
import h5py
import matplotlib.pyplot as plt

In [2]:
# GRADED FUNCTION: initialize_parameters
def initialize_parameters(nx, nh, ny):
  W1 = np.random.randn(nh,nx)*0.01
  b1 = np.zeros((nh,1))
  W2 = np.random.randn(ny,nh)*0.01
  b2 = np.zeros((ny,1))
  parameters = {
        "W1":W1,
        "b1":b1,
        "W2":W2,
        "b2":b2}
  return parameters      

In [3]:
parameters = initialize_parameters(3, 2, 1)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[-2.64530812e-03 -1.37971215e-02 -1.36692358e-02]
 [-3.95741404e-05  2.42648713e-03  8.91458019e-03]]
b1 = [[0.]
 [0.]]
W2 = [[0.0099746  0.00589904]]
b2 = [[0.]]


In [5]:
# GRADED FUNCTION: initialize_parameters_deep
def initialize_parameters_deep(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)
  for l in range(1, L):
    parameters["W" + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
    parameters["b" + str(l)] = np.zeros((layer_dims[l], 1))

    assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
    assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))
  return parameters  

In [6]:
parameters = initialize_parameters_deep([5,4,3])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[0.]
 [0.]
 [0.]]


In [7]:
#sigmoid function
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    cache = Z
    return A, cache

In [8]:
#relu function
def relu(Z):
    A = np.maximum(0,Z)
    assert(A.shape == Z.shape)
    cache = Z 
    return A, cache

In [11]:
# sigmoid_backward
def sigmoid_backward(dA, cache):
    Z = cache
    s = 1/(1+np.exp(-Z))
    dZ = dA * s * (1-s)
    assert (dZ.shape == Z.shape) 
    return dZ

In [13]:
# relu_backward
def relu_backward(dA, cache):
    Z = cache
    dZ = np.array(dA, copy=True) # just converting dz to a correct object.
    # When z <= 0, you should set dz to 0 as well. 
    dZ[Z <= 0] = 0
    assert (dZ.shape == Z.shape)
    return dZ

In [14]:
# GRADED FUNCTION: linear_forward
def linear_forward(A,W,b):
  Z = (np.dot(W,A)+b)
  cache = (A,W,b)
  return Z,cache

In [16]:
# GRADED FUNCTION: linear_activation_forward
def linear_activation_forward(A_prev, W, b, activation):
  if activation=="sigmoid":
    Z, linear_cache = linear_forward(A_prev,W,b)
    A, activation_cache = sigmoid(Z)
  elif activation=="relu":
    Z, linear_cache = linear_forward(A_prev,W,b)
    A, activation_cache = relu(Z) 
  cache=(linear_cache,activation_cache)
  return A,cache  

In [17]:
# GRADED FUNCTION: L_model_forward
def L_model_forward(X, parameters):
  caches = []
  A = X
  L = len(parameters) // 2 
  for l in range(1,L):
    A_prev = A
    A, cache = linear_activation_forward(A_prev,parameters['W' + str(l)], parameters['b' + str(l)], "relu")
    caches.append(cache) 
  AL, cache = linear_activation_forward(A,parameters['W' + str(l)], parameters['b' + str(l)], "sigmoid")
  caches.append(cache) 
  return AL, caches


In [18]:
# GRADED FUNCTION: compute_cost
def compute_cost(AL, Y):
  m = Y.shape[1]
  cost = (-1/m)* (np.dot(Y,np.log(AL).T) +  np.dot((1-Y),np.log(1-AL).T))
  cost = np.squeeze(cost)
  return cost

In [19]:
# GRADED FUNCTION: linear_backward
def linear_backward(dZ, cache):
  A_prev, W, b = cache
  m = A_prev.shape[1]
  dW = (1/m)*np.dot(dZ,A_prev.T) 
  db = (1/m)*np.sum(dZ,axis=1,keepdims=True)
  dA_prev = np.dot(W.T,dZ)
  return dA_prev, dW, db

In [21]:
# GRADED FUNCTION: linear_activation_backward
def linear_activation_backward(dA, cache, activation):
  linear_cache, activation_cache = cache
  if activation == "relu":
    #(≈ 2 lines of code)
    # dZ =  ...
    # dA_prev, dW, db =  ...
    # YOUR CODE STARTS HERE
    dZ = relu_backward(dA, activation_cache)
    dA_prev, dW, db =  linear_backward(dZ,linear_cache)
    # YOUR CODE ENDS HERE
        
  elif activation == "sigmoid":
    #(≈ 2 lines of code)
    # dZ =  ...
    # dA_prev, dW, db =  ...
    # YOUR CODE STARTS HERE
    dZ = sigmoid_backward(dA, activation_cache)
    dA_prev, dW, db = linear_backward(dZ,linear_cache)
  return dA_prev, dW, db  

In [23]:
# GRADED FUNCTION: L_model_backward
def L_model_backward(AL, Y, caches):
  grads = {}
  L = len(caches) # the number of layers
  m = AL.shape[1]
  Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
  dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
  current_cache = caches[L-1]
  dA_prev_temp, dW_temp, db_temp = linear_activation_backward(dAL, current_cache, "sigmoid")
  grads["dA" + str(L-1)]=dA_prev_temp
  grads["dW" + str(L)]=dW_temp
  grads["db" + str(L)] =db_temp
  # Loop from l=L-2 to l=0
  for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 1)], current_cache". Outputs: "grads["dA" + str(l)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        #(approx. 5 lines)
        # current_cache = ...
        # dA_prev_temp, dW_temp, db_temp = ...
        # grads["dA" + str(l)] = ...
        # grads["dW" + str(l + 1)] = ...
        # grads["db" + str(l + 1)] = ...
        # YOUR CODE STARTS HERE
    current_cache = caches[l]
    dA_prev_temp, dW_temp, db_temp = linear_activation_backward(grads["dA" + str(l + 1)], current_cache, activation = "relu")
    grads["dA" + str(l)] =dA_prev_temp
    grads["dW" + str(l + 1)] =dW_temp
    grads["db" + str(l + 1)] =db_temp
    # YOUR CODE ENDS HERE
  return grads  
  

In [24]:
# GRADED FUNCTION: update_parameters
def update_parameters(params, grads, learning_rate):
    """
    Update parameters using gradient descent
    
    Arguments:
    params -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients, output of L_model_backward
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
                  parameters["W" + str(l)] = ... 
                  parameters["b" + str(l)] = ...
    """
    parameters = params.copy()
    L = len(parameters) // 2 # number of layers in the neural network

    # Update rule for each parameter. Use a for loop.
    #(≈ 2 lines of code)
    for l in range(L):
        # parameters["W" + str(l+1)] = ...
        # parameters["b" + str(l+1)] = ...
        # YOUR CODE STARTS HERE 
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
        # YOUR CODE ENDS HERE
    return parameters